name: Lint

on:
  pull_request_target:
    branches: [main]

permissions: write-all

jobs:
  markdownlint:
    name: markdown-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          # 匹配任意md, mdx文件
          files: '**/*.md?(x)'
          ignore: node_modules
          fix: true
