name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'README.md'
      - 'src/**/*.md?(x)'
      - 'docs/**/*.md?(x)'
      - 'blog/**/*.md?(x)'

permissions: write-all

jobs:
  markdownlint:
    name: markdown-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          # 匹配任意md, mdx文件
          files: 'src/**/*.md?(x) docs/**/*.md?(x) blog/**/*.md?(x) README.md'
          ignore: node_modules
          fix: true
